---
- name: Install systemd service file
  template:
    src: "k3s.service.j2"
    dest: /etc/systemd/system/k3s.service
    owner: root
    group: root
    mode: 0644
  register: k3s_systemd_service_file
  notify:
     - daemon-reload
     - start-service
