---
- name: Disable nftables (if installed)
  service:
    name: nftables
    state: stopped
    enabled: no
  ignore_errors: yes

- name: Install iptables
  package: 
    name: iptables
    state: present
