---
- name: "Update and upgrade for RedHat based distributions"
  dnf:
    name: '*'
    update_cache: yes
    state: latest
  when: ansible_os_family == 'RedHat'
  notify: 
    - reboot

- name: "Update and upgrade for Debian based distributions"
  apt:
    update_cache: yes
    upgrade: safe
  when: ansible_os_family == 'Debian'
  notify: 
    - reboot
