---
- name: daemon-reload
  systemd:
    daemon_reload: yes

- name: start-service
  systemd:
    enabled: yes
    name: k3s.service
    state: restarted

- name: reboot
  reboot:
    reboot_timeout: 3600
